

function Twitter_RSS() {
 doGet()
}

function doGet(t) {
 if (t) {
  var e, r = t.queryString ? t.queryString : "362462751664263169";
  if (r.match(/^\d+$/)) {
   var i = CacheService.getScriptCache(),
    a = "ctrlq" + r;
  // if (e = i.get(a), e || (e = getTweets_(r) && i.put(a, e, 60))) return ContentService.createTextOutput(e).setMimeType(ContentService.MimeType.XML)
  var jsonResult=JSON.stringify(getTweets_(r));
  return ContentService.createTextOutput(jsonResult).setMimeType(ContentService.MimeType.JSON)

  } else e = "Please enter a valid Twitter Widget ID. For support, send an email to amit@labnol.org or tweet @labnol with the widgetID# " + r;
  return ContentService.createTextOutput(e)
 }


}

function getTweets_(t) {
 try {
  var e = JSON.parse(UrlFetchApp.fetch("https://cdn.syndication.twimg.com/widgets/timelines/" + t, {
   muteHttpExceptions: !0
  }).getContentText());
  if (!e || !e.body) return "Could not fetch the Twitter feed. Please retry after few minutes or send the link " + url + " to amit@labnol.org for support";
  e = e.body.replace(/\n+/gm, "");
  //var r = '<?xml version="1.0"?>';
     var result=[];

  //r += ' <rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:media="http://search.yahoo.com/mrss/">', r += " <channel><title>Twitter RSS Feed for Widget " + t + " - Generated by ctrlq.org</title>", r += " <link>https://ctrlq.org/?source=ctrlq.org&amp;twitter=" + t + "</link>", r += ' <atom:link href="' + ScriptApp.getService().getUrl() + "?source=ctrlq.org&amp;twitter=" + t + '" rel="self" type="application/rss+xml" />', r += " <description>Twitter RSS feed updated on " + new Date + ". Get your own Twitter RSS Feeds at http://www.labnol.org/?p=28149</description>";
  for (var i, a = new RegExp(/<li class="timeline-TweetList-tweet.*?>(.*?)<\/li>/g); null !== (i = a.exec(e));) {
    var individual=[];
   var o = i[1],
    n = o.match(/datetime="(.*?)"/);
   n = n ? n[1] : "";
   var l = o.match(/data\-tweet\-id="(.*?)"/);
   l = l ? l[1] : "";
   var c = o.match(/\"(https:\/\/twitter\.com\/[^\s]+\/status\/\d{5,})\"/);
   c = c ? c[1] : "https://ctrlq.org/";
   var s = o.match(/TweetAuthor\-name.*?>(.*?)<\/span>/);
   s = s ? s[1] : "ctrlq.org";
   var m = o.match(/data\-src\-2x="(.*?)"/);
   m = m ? m[1] : "";
   var p = o.match(/p class="timeline-Tweet-text".*?>(.*?)<\/p>/);
    
    if(p){
      p=p[1];
      individual.push(
        {titulo: p.replace(/<[^>].*?>/g, ""),pubDate: n,guid: l,link: c,author: s,mediaurl: m,linkImagen: c,linksrc: m,description: p}
      );
      result.push(individual)
    }else{
      p="";
    }

  }
  return result
 } catch (d) {
  return "Could not fetch the Twitter feed. Please retry after few minutes or send this message - " + d.toString() + "  - to amit@labnol.org for support"
 }
}


